name: Deploy to Digital Ocean
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DO_GIT_PRIVATE_KEY }}
          name: do_git
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: ignore
      - name: SSH to DO
        run: ssh git@159.65.93.127