name: Deploy to Digital Ocean
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Create private key
       uses: appleboy/ssh-action@v1.0.0
       with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USER }}
          key: ${{ secrets.DO_GIT_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al