name: Deploy to Digital Ocean
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Create private key
       run: |
          mkdir -p -m 700 ~/.ssh
          echo "${{ secrets.DO_GIT_PRIVATE_KEY }}" >> ~/.ssh/do_git
          chmod 600 ~/.ssh/do_git
          ls -l ~/.ssh
          ls -l ~/.ssh/do_git
          ssh -o "StrictHostKeyChecking no" git@159.65.93.127