name: Deploy to Digital Ocean
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Create private key
       uses: appleboy/ssh-action@v1.0.0
       with:
          host: 159.65.93.127
          username: git
          key: ${{ secrets.DO_GIT_PRIVATE_KEY }}
          port: 22
          script: |
            whoami
            ls -al