name: Deploy to Digital Ocean
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        run: |
          mkdir -p -m 700 ~/.ssh
          echo "${{ secrets.DO_GIT_PRIVATE_KEY }}" >> ~/.ssh/do_git
          chmod 600 ~/.ssh/do_git
          eval `ssh-agent -s`
          ssh-agent -a /tmp/ssh_agent.sock > /dev/null
          ssh-add ~/.ssh/do_git
      - name: SSH to DO server
        run: ssh -o "StrictHostKeyChecking no" -i ~/.ssh/do_git git@159.65.93.127

